"""empty message

Revision ID: 5c51e36125db
Revises: 9bb2562e2dc5
Create Date: 2019-09-18 23:47:42.457540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c51e36125db'
down_revision = '9bb2562e2dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('rating', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'good')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('good', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'rating')
    # ### end Alembic commands ###
